from abc import ABC, abstractmethod

class IGpio(ABC):
    @abstractmethod
    def set_pin(self, pin: int, value: bool) -> bool: ...
    @abstractmethod
    def read_pin(self, pin: int) -> bool: ...

class ICamera(ABC):
    @abstractmethod
    def capture(self) -> bytes: ...
    @abstractmethod
    def start_stream(self, callback) -> bool: ...
    @abstractmethod
    def stop_stream(self) -> None: ...

class ILed(ABC):
    @abstractmethod
    def set_color(self, r: int, g: int, b: int) -> bool: ...
    @abstractmethod
    def blink(self, frequency: float) -> bool: ...
    @abstractmethod
    def off(self) -> bool: ...

class IBuzzer(ABC):
    @abstractmethod
    def beep(self, duration: float, frequency: float) -> bool: ...
    @abstractmethod
    def off(self) -> bool: ...
